// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gcqdpdttdznbvqmuoknw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdjcWRwZHR0ZHpuYnZxbXVva253Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk0NzY3NjMsImV4cCI6MjA1NTA1Mjc2M30.XXHQCsIaWHcNxI_934wL9TJKqid_m_SOKUPqYbBPXEw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);